spring:
  #rabbitmq配置
  rabbitmq:
    #服务器地址
    host: 47.108.253.100
    #用户名
    username: admin
    password: admin@123
    #虚拟主机
    virtual-host: /
    #端口
    port: 5672
    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        #消费者最大数量
        max-concurrency: 10
        #限制消费者每次只处理一条消息
        prefetch: 1
        #默认启动容器
        auto-startup: true
        #被拒绝时进入队列
        default-requeue-rejected: true
    template:
      retry:
        #发布重试
        enabled: true
        #重试时间
        initial-interval: 1000ms
        #重试最大次数默认三次
        max-attempts: 3
        #重试最大时间间隔
        max-interval: 10000ms
        #重试间隔系数
        multiplier: 1

  thymeleaf:
    #关闭缓存
    cache: false
  redis:
     #超时时间
     timeout: 10000ms
     #服务器地址
     host: 47.108.253.100
     #服务器端口
     port: 6379
     #数据库
     database: 0
     #密码
     lettuce:
      pool:
       #最大连接数，默认8
       max-active: 1024
       #最大连接阻塞等待时间，默认-1
       max-wait: 10000ms
       #最大空闲连接
       max-idle: 200
       #最小空闲连接
       min-idle: 5
   #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.108.253.100:3306/seckill?
      useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: test
    password: 90125073asD@
    hikari:
     pool-name: DateHikariCP
     minimum-idle: 5
       # 空闲连接存活最大时间，默认600000（10分钟）
     idle-timeout: 180000
       # 最大连接数，默认10
     maximum-pool-size: 10
       # 从连接池返回的连接的自动提交
     auto-commit: true
       # 连接最大存活时间，0表示永久存活，默认1800000（30分钟）
     max-lifetime: 1800000
       #连接超时时间，默认30000（30秒）
     connection-timeout: 30000
     #测试心跳
     connection-test-query: SELECT 1
  web:
    resources:
      cache:
       cachecontrol:
         max-age: 600
      chain:
            #资源链中启用缓存，默认启用
         cache: true
            #启用资源链，默认禁用
         enabled: true
            #启用压缩资源(gzip,brotli)解析,默认禁用
         compressed: true
      #静态资源位置
      static-locations: classpath:/static/
      add-mappings: true
# Mybatis-plus配置
mybatis-plus:
  #配置Mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置别名
  type-aliases-package: com.zhuomo.seckill_demo.pojo
## Mybatis SQL 打印(方法接口所在的包，不是Mapper.xml所在的包)
logging:
  level:
   com.zhuomo.seckill_demo.mapper: debug